---
title: "**Uploading external data to the DST servers**"
author: "Cæcilie Stilling Denholt & Mikkel Porsborg Andersen"
date: "`r format(Sys.time(), '%d. %B %Y')`"
output:
  pdf_document
---

If you need a dataset uploaded to the DST servers, please coordinate this with your older and then follow the procedure below:

1.  If your data is approved in Region Hovedstaden, we will have to do an internal transfer (*intern overdragelsesaftale*) of the data. You should send the following information to the datamanager: a) description of the data and the categories of data, b) the project manager listed on the approval, and c) the approval number.

    If your data is approved elsewhere, we will have to do disclosure agreement (*videregivelsesaftale*), and you should contact your data responsible institution for guidance on this process.

When the procedure above has been executed, adhere to the following steps:

2.  Go to DDV at remote.dst.dk → find your project folder → pick the latest project version → go to ‘Dataindhold’ → scroll down to ‘Øvrige datakilder’ Here, you should check whether the database is registered on the project folder. If it is, go to step 3. If it is not, you should contact the datamanagers with the following information (along with the info in step 3):

-   Which database you need uploaded, and for which project folder
-   5-10 lines about why the database is relevant for the project, and what it will be used for in relation to the overall aim of the specific project folder (can be found in DDV under the latest project version)

3.  Prepare your data as a SAS-dataset. Adhere to [**DST’s rules**](https://www.dst.dk/en/TilSalg/data-til-forskning/anmodning-om-data/tilknytning-af-ovrige-data) (e.g. no free text variables).

    Prepare a list of variables and a short description for each variable.

Lastly, book a meeting with the datamanager, who will help with the upload of data.
